# Generated by Django 5.0.3 on 2024-03-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_digital_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='postalcode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='nearest_town',
            new_name='town',
        ),
    ]
